---
title: "code for real"
author: "Yuxuan"
date: "16/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library("tidyverse")
library("car")
library("rpart")
library("rpart.plot")
library("nnet")
library("randomForest")
library("effects")


library(zoo)

```

```{r}
library(dplyr)
library(zoo)
account <- read.csv("ACCOUNT_DATASET_ST.csv")
philine <- read.csv("PHLINE_DATASET_ST.csv")
city <- read.csv("CITY_DATASET_ST.csv")

acc_phi <- inner_join(account, philine, by = "acc_num")
head(acc_phi)
dplyr::left_join(acc_phi,city,by="bill_city")->fulldata
#data
fulldata %>% mutate(ph_k_date = as.Date(fulldata$ph_k_date), st_date = as.Date(fulldata$st_date)) -> fulldata
#date
fulldata %>% mutate(ph_k_date = as.Date(fulldata$ph_k_date), st_date = as.Date(fulldata$st_date)) -> fulldata
head(fulldata)
levels(fulldata$data_plan_m8)

#missing value indicator, 1 for missing, 0 otherwise
#fulldata %>% mutate(missing_phdate = ifelse(is.na(fulldata$ph_k_date) == 1, 1, 0)) -> fulldata
#data plan prices
fulldata %>% mutate(data_plan_m8 = as.factor(data_plan_m8)) -> fulldata

#data roam volum
levels(fulldata$data_plan_m8)
fulldata %>% mutate(data_volume = ifelse(fulldata$data_plan_m8 == "10GB($65)", 10, 15)) %>% mutate(data_volume = ifelse(fulldata$data_plan_m8 == "15GB($80)", 15, 25)) %>% mutate(data_volume = as.numeric(data_volume))-> fulldata

fulldata$data_left<-as.numeric(fulldata$data_left)
fulldata$data_volume<-as.numeric(fulldata$data_volume)
#data left over
fulldata %>% mutate(data_left = as.numeric(data_volume - mon_data)) -> fulldata

#change to levels
#fulldata$bill_city%>%as.factor(fulldata$bill_city)


#churn binary
fulldata %>% mutate(churn = factor(fulldata$churn)) -> fulldata
levels(fulldata$churn)
levels(fulldata$data_plan_m8)
head(fulldata)
#
fulldata$ph_k_date <- as.POSIXct(na.approx(fulldata$ph_k_date), origin = "2014-7-28")


```

```{r}
fulldata$ph_k_date<-time(fulldata$ph_k_date)
fulldata$cr_score<-as.factor(fulldata$cr_score)
fulldata$churn<-as.factor(fulldata$churn)
```


```{r}
#est, val, holdout groups
fulldata %>% filter(Sample == "Estimation")%>%select(-Sample) -> est.d
fulldata %>% filter(Sample == "Holdout")%>%select(-Sample) -> hold.d
fulldata %>% filter(Sample == "Validation")%>%select(-Sample) -> val.d
```


```{r}
as.factor(est.d$churn)->est.d$churn
levels(est.d$churn) 

head(est.d)
fit.logistic <- glm(churn ~.-bill_city,family = binomial,data=est.d)


fit.test <- glm(formula = churn ~ ., family = "binomial", data = est.d)
summary(fit.logistic)

#logistic
fit.logistic <- glm(churn ~.,family = binomial,data=est.d)
summary(fit.l2)
fit.l2 <- glm(churn ~., family = binomial(), data = est.d)
#step wise
step.logs <- step(fit.logistic, direction = "forward")
step.l2 <- step(fit.l2, direction = "forward")

predict(fit.l2,hold.d,type = "response")%>%as.vector()->pll

pll

summary(fit.test)

```


```{r}
head(est.d)
install.packages("nnet")
library(nnet)
require(neuralnet)
#Running a neural network
head(est.d)
est.d%>%select(-bill_city,-ph_num,-ph_k_date)->est.d
Model4.NeuNet <- nnet(formula =churn~.,
                       data = est.d,
                       decay = 0.01, # decay parameter
                       size = 3)

Model4.NeuNet$value

est.d%>%select(-bill_city,-ph_num)->est.d
hold.d%>%select(-bill_city,-ph_num)->hold.d

#predict(Model4.NeuNet,val.d,type = c("raw","class"))->pred.m4
predict(Model4.NeuNet,val.d,type ="raw")
pred.m4
table(val.d$churn,predict(Model4.NeuNet,val.d,type ="class"))  
# Predicting on train set

predict(Model4.NeuNet,hold.d,type = "prob")->pred.m4
pred.m4
```

```{r}
est.d$churn<-as.factor(est.d$churn)
head(est.d)

# Predicting on train set
predTrain <- predict(Model.RanFor, val.d, type = "response")
length(predTrain)
# Checking classification accuracy
length(val.d$churn)
table(predTrain,val.d$churn)  
importance(Model.RanFor) 

est.d%>%select(-bill_city,-ph_num,-acc_num)->est.d
hold.d%>%select(-bill_city,-ph_num,-acc_num)->hold.d
head(est.d)
Model.RanFor <- randomForest(formula =churn~.,
                              data =est.d,
                              importance = TRUE,
                              ntree = 400, mtry = 4)


# test set


#predict(Model4.NeuNet,val.d,type = c("raw","class"))->pred.m4
pred <- predict(Model.RanFor, val.d,type="prob")
pred
table(val.d$churn,predict(fit.l2,val.d,type ="response"))  
pred%>%as.data.frame()->pred
result<-NULL%>%as.data.frame()

predict(fit.l2,val.d,type = "response")%>%as.vector()->pll
length(pll)
sub$score....pred<-(pll+sub$score....pred)/2
d$score->s
length(s+pll)
d$score<-(pll*0.+s)/2
head(d)
d$ph_num
data.frame(ph_num=hold.d$ph_num,score<-pred)->sub
write.csv(d, 'Team3.csv')

```
